#it takes around 45 minutes to execute!
import BNC_nouns_extractor
import reviews_noun_extractor
import counter_occurrences
import KL_divergence
import Movie
import movie_extractor 

def execute_pipeline():

    corpora_BNC = BNC_nouns_extractor.BNC_nouns_extractor(root_bnc_directory, destiny_bnc_nouns)
    
    corpora_reviews = reviews_noun_extractor.reviews_noun_extractor(your_database_directory, destiny_reviews_nouns)

    KL_values = KL_divergence.KL_nouns_values(corpora_BNC, corpora_reviews)

    aspects_dict = KL_divergence.epsilon_aspects_extraction(KL_values, KL_threshold, "aspects_pipeline.txt")

    # parei aqui
    set_of_movies = []
    #a pasta xml_reviews é de teste, reunindo um conjunto pequeno de reviews separadamente 

    directory_path = "C:\\Users\\User\\Desktop\\ic\\xml_reviews"

    movie_extractor.movie_extractor(directory_path, aspects_dict, set_of_movies, KL_threshold)


    for movie in set_of_movies:
        movie.sentence_filtering()



if __name__ == '__main__':


    generate_txt_bnc_nouns = False
    destiny_bnc_nouns = "none"
    # destiny_bnc_nouns = "corpora_BNC.txt"
    root_bnc_directory = "C:\\Users\\User\\Desktop\\ic\\ota_20.500.12024_2554\\2554\\Texts"

    your_database_directory = "C:\\Users\\User\\Desktop\\ic\\Reviews\\HetRec_CoreNLP" 
    destiny_reviews_nouns = "corpora_reviews.txt"

    #value chosen for the KL divergence threshold
    KL_threshold = 2000 

    execute_pipeline(destiny_bnc_nouns, root_bnc_directory, )

    # files generated by this code:
    # "KL_nouns.txt" - contains each noun present in the reviews and its KL value
    # "aspects_pipeline.txt" - contains each aspect presented in the reviews and its KL value